version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=development_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gamekeys
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
    depends_on:
      - db
      - redis
    command: >
      bash -c "python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend
    command: npm start

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=development_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gamekeys
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    command: celery -A gamekeys worker -l INFO

  celery-beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=development_secret_key
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gamekeys
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - backend
      - redis
    command: celery -A gamekeys beat -l INFO

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gamekeys
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: